# Generated by Django 4.2.6 on 2023-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_introduce_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='accounts/profile_imgs'),
        ),
    ]
